### ISSUE TITLE
Playlist Download Not Grabbing All Files

### ISSUE THREAD

**Issue by Dan-Wood** [regisb/spotify-onthego#12]
Right so my playlist is pretty large, around 388 songs.

Looks like it only downloads a few then stops, I'm up to 103 and no matter how many times I re-run  the below

spotify-playlist "Massive" /root/music/

I never get further than that 103.

```
~# ls -lah music/ | wc -l
103
root@poke:~# df -h
Filesystem         Size  Used Avail Use% Mounted on
/dev/ploop11048p1  6.8G  1.4G  5.1G  22% /

```

**Comment by Dan-Wood** [comment]
Playlist - https://play.spotify.com/user/msdathk/playlist/3HXm13Cik1lje31z1frW95

**Comment by regisb** [comment]
Good catch! The script was only downloading the first 100 results from the API. I just pushed a fix to iterate over all items of a playlist. The corresponding release number is 0.0.5.
