### ISSUE TITLE
Download path can be altered by playlist name

### ISSUE THREAD

**Issue by aboutsko** [regisb/spotify-onthego#15]
http://open.spotify.com/user/youzoun/playlist/2POsysj8dTuOCAMPYVsgeO

This playlist contains a '/' in its name, the download path reuses it and creates a subdirectory. Ideally, only one directory is created with the whole name of the playlist.

**Comment by regisb** [comment]
What command do you run exactly?

**Comment by aboutsko** [comment]
spotify-playlist "Minimal*" directory/

**Comment by regisb** [comment]
You are absolutely right, this is incorrect behaviour. Fixed.
