### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by Dan-Wood** [regisb/spotify-onthego#20]
Downloading/unpacking eyeD3==0.7.9 (from spotify-onthego==0.0.5)
  Could not find a version that satisfies the requirement eyeD3==0.7.9 (from spotify-onthego==0.0.5) (from versions: )
No distributions matching the version for eyeD3==0.7.9 (from spotify-onthego==0.0.5)

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
```

```
# python --version
Python 2.7.3
```

```
# pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

```

**Comment by regisb** [comment]
@Dan-Wood thanks for the heads-up! I just pushed an updated requirements file that should solve the issue. Please re-open if it's not the case.
