### ISSUE TITLE
Ability to skip tracks (if youtube lists as whole album)

### ISSUE THREAD

**Issue by plittlefield** [regisb/spotify-onthego#24]
Is there a way to skip tracks as it works?

I came across a situation today where it found a YouTube entry (with the same name as the single track) but it was the whole album!

e.g.

```
spotify-playlist "Discover Weekly" "/Music/SpotifyOnTheGo/2017-08-21/"
Downloading playlist 'Discover Weekly' (id=37i9dQZEVXcFcGn24UDENb) from owner 'spotify'
++ Processing Adept - Sleepless
    Downloading https://www.youtube.com/watch?v=BQKs2XxWTlo to /tmp/Adept - Sleepless (Full Album 2016).m4a

```
...which ofcourse would take too long and be too large.

Any ideas?

**Comment by Dan-Wood** [comment]
Only way I could see a fix for this one is to check the title and ignore if it's got those words..

Would be good if we had this as you could prefer the titles with the word "original" and ignore things like full album or live, so many songs I've gotten are terrible quality as they're either a cover song or live.

Preferred titles should be

1 remastered
2 original

Ignored

1 full album
2 live
3 cover

Any objections?

**Comment by plittlefield** [comment]
Nope, maybe include 'Official' in preferred as well?

**Comment by regisb** [comment]
Hi @Dan-Wood @plittlefield,

Thanks for your input and ideas! And sorry for the late reply, I had almost zero access to the Internet for about two weeks.

I understand your problem. For now, there is a quick-and-dirty fix. By default, downloads are skipped if the file already exists. So you can simply create an empty file with the right name to prevent the download:

    touch "/Music/SpotifyOnTheGo/2017-08-21/Adept - Sleepless.mp3"

Now, I know this is *not* an ideal solution. I understand the issue you are both facing, but I don't think that trying to manually improve the song search algorithm is the right solution. IMHO, improving the song search results is Youtube's job, not ours. We are bound to do a worse job at song searching than the Youtube search algorithm itself. Plus, my intuition tells me that manual tuning of the search parameters is going to cause many erroneous results down the road.

There are other solutions. What I would suggest is to create an interactive mode, activated by the `-i/--interactive` CLI flag. In interactive mode, the user is presented with the list of youtube results and can manually select the one he wants to download. Something like:

```
[1] Adept - Sleepless (Full Album 2016) https://www.youtube.com/watch?v=BQKs2XxWTlo
[2] Adept - Sleepless (Lyrics) https://www.youtube.com/watch?v=v6C19rq3ycQ
...
[10] ...
Select the video to download (default: 1) (next/previous/abort):
```

So, the user can automatically download playlists, as usual, and then fine-tune results by manually removing some songs and restarting the command with the `-i` flag.

Thoughts?

**Comment by plittlefield** [comment]
Brilliant idea, go for it.

You beat me to that suggestion by a few paragraphs.

Nice explanation and reasoning though.

I'm actually excited about making a difference to something, it makes a
nice change to give something back.

Good work.

Paully

**Comment by regisb** [comment]
Great! @plittlefield would you like to implement the feature yourself? You would open a pull request with your proposed changes and I would proofread it, then eventually suggest changes or implement them myself.

**Comment by plittlefield** [comment]
Ah, my apologies for the confusion. I am no programmer (well, I do BASH and
PERL) but not compentant enough to make a change to your app!

**Comment by regisb** [comment]
No worries, I'll work on it.

**Comment by plittlefield** [comment]
Thanks, no rush and sorry I could not help in that way :-)

**Comment by Dan-Wood** [comment]
I like the idea, but relying on YouTube search doesn't quite make sense. I'm getting live or covered songs from completely different artists these videos and that wouldn't happen if we're searching Artist Song title, right?

You'd expect a correct result of that was the case, however it's not happening. I'd like to see some options of those keywords, up to you though, you're the developer.

**Comment by plittlefield** [comment]
Maybe --keywords should be an option!

**Comment by regisb** [comment]
@Dan-Wood I'm not sure I understand your last comment. Are you aware that, in spotify-onthego, songs from a spotify playlist are searched on Youtube? We perform a search of the form "<song title> <artist>" (title and artist separated by an empty space). Then we download the audio of the top result directly from Youtube.

Can you give examples of artist/songs that produce bad results? (cover songs, live performance, etc.) I'm quite sure that the downloaded songs are the top Youtube result.

**Comment by regisb** [comment]
I just pusblished v1.0.4 which introduces interactive mode. Please re-open this issue or create a different one if the feature does not match your expectations.

**Comment by plittlefield** [comment]
The only time that you can get these clocks and the plumber's a one is the
O'Neill and the clocks back home x inandrew's thanksplease send the
