### ISSUE TITLE
ConnectionError: HTTPSConnectionPool Max retries exceeded

### ISSUE THREAD

**Issue by plittlefield** [regisb/spotify-onthego#25]
Hello,

Is this because the website is down or just bad timing on my part?

How can I skip the first 7 that were successful if I try again later today?

https://pastebin.com/TFKVjyGM

Paully

**Comment by regisb** [comment]
Hi Paully! I believe you experienced a connection issue. Was your computer temporarily disconnected from the web? You can just retry downloading the playlist. The tracks that were previously downloaded should be automatically skipped.

**Comment by plittlefield** [comment]
Great, nice it remembers! Yes, that worked and I must have just hit an internet blockage. Sorry for the hassle. All good now, and I shall close the issue.
