### ISSUE TITLE
spotify-playlist unicodedecodeerror

### ISSUE THREAD

**Issue by superurbi** [regisb/spotify-onthego#26]
spotify-playlist unicodedecodeerror when retrieving mp3 with names in spanish:
 'ascii' codec can't decode byte 0xc3 in position 52: ordinal not in range(128)

-> for instance this is the error: 

++ Processing Juan Magán - Déjate Llevar
    Downloading http://www.youtube.com/watch?v=9-rzG8qwkjA to /tmp/Juan Magan, Belinda, Manuel Turizo, Snova, B-Case - Déjate Llevar.webm
Traceback (most recent call last):
  File "/usr/local/bin/spotify-playlist", line 11, in <module>
    load_entry_point('spotify-onthego==1.0.4', 'console_scripts', 'spotify-playlist')()
  File "/usr/local/lib/python2.7/dist-packages/onthego/cli.py", line 52, in download_playlist
    youtube_downloader.audio(track)
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 48, in audio
    self.convert_or_copy(audio_file_path, track)
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 61, in convert_or_copy
    id3.tag(dst_path, track)
  File "/usr/local/lib/python2.7/dist-packages/onthego/id3.py", line 13, in tag
    audiofile = eyed3.load(filepath)
  File "/usr/local/lib/python2.7/dist-packages/eyed3/core.py", line 61, in load
    path = pathlib.Path(path.encode(sys.getfilesystemencoding()))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 52: ordinal not in range(128)

**Comment by regisb** [comment]
Hi, thanks for taking the time to open this issue! I suspect that your file system is not using UTF8 encoding. 

1. Which operating system are you using ?
2. What is the output of the `locale` command?
3. What is the output of the `python -c "import sys; print(sys.getfilesystemencoding())"` command?

**Comment by superurbi** [comment]
I had some issues with the system language, because I could't use my keyboard layout correctly in terminal sessions and I tried solving it issuing some commands posted in ubuntu forums...

1. I use Ubuntu 17.10

2. locale command output:
LANG=es_ES.UTF-8
LANGUAGE=es:en_GB:en
LC_CTYPE=es_ES.UTF-8
LC_NUMERIC=es_ES.UTF-8
LC_TIME=es_ES.UTF-8
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY=es_ES.UTF-8
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER=es_ES.UTF-8
LC_NAME=es_ES.UTF-8
LC_ADDRESS=es_ES.UTF-8
LC_TELEPHONE=es_ES.UTF-8
LC_MEASUREMENT=es_ES.UTF-8
LC_IDENTIFICATION=es_ES.UTF-8
LC_ALL=

3.  python -c "import sys; print(sys.getfilesystemencoding())"
UTF-8

thanks in advance!

**Comment by regisb** [comment]
It's really hard to debug this without access to your machine. I suggest you uninstall the current ` spotify-onthego` version and install the python 3 version:

    sudo pip uninstall spotify-onthego
    pip3 install spotify-onthego

**Comment by superurbi** [comment]
great! I followed those steps and now it works perfectly!
thanks!

**Comment by regisb** [comment]
Great! So I'll close this issue. However, I haven't really solved the issue for Python 2. Could you give me the **exact** command you were trying to run and that was failing?

**Comment by superurbi** [comment]
the command was this:
spotify-playlist "40*" .

**Comment by regisb** [comment]
Ok, I suspect you had an incorrect version of eyed3. Can you give me the output of:

    pip freeze | grep eyeD3

**Comment by superurbi** [comment]
eyeD3==0.8.4

**Comment by regisb** [comment]
Awesome! I managed to reproduce the bug with this version of eyed3. I'll make a new release that addresses this.

**Comment by regisb** [comment]
I'm glad we investigated this issue @superurbi, there was indeed an issue!
