### ISSUE TITLE
failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by JacquesBSTX** [regisb/spotify-onthego#30]
Hi, I have tried to install the project which is a very interesting one, however, I am having certain issues related to the magic library. Here is the screen caption of the answer I am getting when I run the following command:
![image](https://user-images.githubusercontent.com/58628891/70375206-62b35800-18fb-11ea-89cf-1571355a5d8b.png)

Is there any way to correct this? I have tried re-installing the magic library but I am still getting the same error. Thanks in advance for your collaboration.

Cheers,

Thomas

**Comment by JacquesBSTX** [comment]
I finally solved the issue with homebrew !! :)

**Comment by regisb** [comment]
Good job investigating this! We should take the opportunity to improve the documentation, so I'll keep this issue open until I have time to work on this project again. Maybe during the Christmas holidays.

**Comment by JacquesBSTX** [comment]
Hi,
I actually have another issue. I am having trouble with the credentials that I have input and so I am wondering how to reset all the elements of the token.
![Uploading image.png…]()

**Comment by regisb** [comment]
Unless I'm mistaken, the latest release of eyed3 does not depend on the `magic` package. Hence, the libmagic library is no longer required.
